---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: eu-central-1
    prefix: staging
    az: eu-central-1a
  
  tasks:
    - name: create vpc
      ec2_vpc:
        state: present
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
        resource_tags: '{"Name": "{{ prefix }}_vpc"}'

        subnets:
          - cidr: 10.1.0.0/24
            az: "{{ az }}"
            resource_tags: '{"Name": "{{ prefix }}_subnet_public"}'
          - cidr: 10.2.0.0/24
            az: "{{ az }}"
            resource_tags: '{"Name": "{{ prefix }}_subnet_private"}'
          - cidr: 10.3.0.0/24
            az: "{{ az }}"
            resource_tags: '{"Name": "{{ prefix }}_subnet_private"}'
        internet_gateway: yes
        route_tables:
          - subnets:
              - 10.2.0.0/24
              - 10.3.0.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc

    - name: write vpc id to {{ prefix }}_vpc_info file
      shell: echo "{{ prefix }}"_vpc":" "{{ vpc.vpc_id }}"
                      > "{{ prefix }}"_vpc_info

    - name: write subnets id to {{ prefix }}_vpc_info file
      shell: echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}"
                      > "{{ prefix }}"_vpc_info
      with_items: vpc.subnets



